### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by dirtyboi** [subarnab219/Web-Scraping-X-using-beautiful-soup#1]
Hey there!

I saw you using BeautifulSoup so i thought you could need some [Scrapy](https://scrapy.org/) in your scraper.

How about it? You could implement crawling rules much quicker!

BR,

Dirty Boi

**Comment by subarnab219** [comment]
You I have the scrapy code as well just not in git. Scrapy is way faster
than soup.

Thanks for the suggestion :)

**Comment by dirtyboi** [comment]
Cool!

You're welcome!

BR,

Dirty Boi
